#!/bin/bash

case $1 in

build)
    javac App.java
    ;;

package)
    jar -cfe App.jar App App.class
    ;;

run)
    java App
    ;;

*)
    javac App.java
    jar -cfe App.jar App App.class
    java App
    ;;

esac